FROM bellsoft/liberica-openjdk-alpine:11
COPY build/libs/client-service-0.0.1-SNAPSHOT.jar client-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/client-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080
